export const ERROR_CODES = {
  // Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",
  // Auth
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_EXPIRED_TOKEN: "AUTH_EXPIRED_TOKEN",
  GUEST_NOT_ALLOWED: "GUEST_NOT_ALLOWED",
  GUEST_CHARACTER_LIMIT: "GUEST_CHARACTER_LIMIT",
  GUEST_USAGE_LIMIT: "GUEST_USAGE_LIMIT",
  TOKEN_INVALID: "TOKEN_INVALID",
  // User
  USER_NOT_FOUND: "USER_NOT_FOUND",
  // Story
  STORY_NOT_FOUND: "STORY_NOT_FOUND",
  STORY_NOT_OWNER: "STORY_NOT_OWNER",
  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
  CHARACTER_NOT_FOUND: "CHARACTER_NOT_FOUND",
  // Chat
  CHAT_ROOM_NOT_FOUND: "CHAT_ROOM_NOT_FOUND",
  CHAT_CHARACTER_NOT_FOUND: "CHAT_CHARACTER_NOT_FOUND",
  // Common
  BAD_REQUEST: "BAD_REQUEST",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
